### PR TITLE
.github/workflows/ci-sage.yml: Update

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes the Cygwin workflow and makes other updates to the tested platforms

### CODE REVIEW

**Comment by fingolfin** [comment]
Fetching the sage git fails:

git_trac.git_error.GitError: git returned with non-zero exit code (128) when executing "git merge FETCH_HEAD"
68
    STDERR: fatal: refusing to merge unrelated histories

**Comment by mkoeppe** [comment]
Yes, I'm working on it. I have seen this strange error before, I think it's a bug in git-trac.

**Comment by mkoeppe** [comment]
OK, this should work. If you could cancel the previous pending CI runs, this will go through faster

**Comment by mkoeppe** [comment]
OK, this should work. If you could cancel the previous pending CI runs, this will go through faster

**Comment by mkoeppe** [comment]
Seems to work, catches testsuite errors

**Comment by w-bruns** [comment]
Is there something to do on the Normaliz side? For example, merging this PR?

**Comment by mkoeppe** [comment]
Yes, this PR is ready for merging.

**Comment by mkoeppe** [comment]
Thanks for merging! Is the workflow currently disabled? I don't see it running in the GH Actions

**Comment by w-bruns** [comment]
Sorry, I had forgotten that Julian Rüth had switched this workflow of when he adapted Normaliz to e-antic 1.0.0  and had to run many tests.

Meanwhile e-antic 1.0.0-rc13 is compatible to Flint 2.7, and, together with Julian's suggestions for Normaliz, the performance is acceptable. 

From the Sage viewpoint, what should we do: stay with e-antic 0.1.9 in the next release or switch to 1.0.0?

**Comment by w-bruns** [comment]
PS. Please reactivate the workflow.

**Pull request merged**
