### PR TITLE
configure.ac: Another fix for -larb vs -lflint-arb

### PR DESCRIPTION
**Pull request by mkoeppe**
... to fix a failure reported in https://trac.sagemath.org/ticket/27952#comment:147

### CODE REVIEW

**Comment by mkoeppe** [comment]
Could we get a new source release including this fix please?

**Comment by w-bruns** [comment]
I am making a prerelease 3.8.7 today.

**Comment by w-bruns** [comment]
What is the situation in regard to nauty?

**Comment by w-bruns** [comment]
Prerelease published

**Comment by w-bruns** [comment]
Because of a mistake I had to renew this release. Please check that it contains the changes for which it has been made.

**Comment by mkoeppe** [comment]
> What is the situation in regard to nauty?

Nothing new - I have postponed working on the nauty-on-trusty problem until after the Sage 9.2 release.

**Comment by mkoeppe** [comment]
> Prerelease published

Thank you!

**Comment by w-bruns** [comment]
Note that both branches master and release now containa Trusty build in .tavis.yml. The branch rational_lattice will be deleted.

**Pull request merged**
