### PR TITLE
Replace explicit ::iterator with auto keyword

### PR DESCRIPTION
**Pull request by fingolfin**
... in most places where it is possible. The resulting code is often
easier to read and maintain. This also enables future refactoring,
e.g. use of ranged for-loops.

Caveat: use of `auto` may not work with OpenMP, but I can't test that locally. So the Travis tests using OpenMP may very well fail, in which case I can update this PR. But before I invest that work, it'd be good to know if there is any interest in this at all, otherwise I'll just drop it.

### CODE REVIEW

**Comment by w-bruns** [comment]
Syntactically o.k., but it fails at run time. My impression: at least one loop does not terminate properly. For example we see bad_alloc, usually an indication that memory is exhausted.

Is it possible to start a new branch with the present master and this pull request (in order not to change the master branch) ? Otherwise I merge, pull, start a new branch, reset master and push again.

**Comment by w-bruns** [comment]
Before I forget: thanks for cleaning this up!

A remark on history: in the first years of C++ coding there was no auto. So the older parts of the code have those complicated iterator definitions.

**Comment by w-bruns** [comment]
With the second commit some builds were successful, the three Linux ones without OpenMP and one more. Others failed because of syntax problems. I guess the latter were cured with the last commit.

**Comment by fingolfin** [comment]
I am glad you like the general direction of this PR! That means it is worthwhile for me to debug and fix it -- I was aware of the crash, but just didn't want to bother with it before I knew whether you liked the general idea of this (if you didn't, then it would have been a waste of time to debug it).

Anyway, of course you can also try it out. The easiest way would be to simply clone my form of the Normaliz repository, and then check out my branch `mh/use-auto`. Slightly more advanced is to work within an existing clone of the main Normaliz repository, but add my repository as a `git remote`, then access it. Something like this should do that, executed inside an existing Normaliz.git clone:
```
git remote add fingolfin https://github.com/fingolfin/Normaliz
git fetch fingolfin # ask git to fetch all my branches
git checkout mh/use-auto
```

**Comment by w-bruns** [comment]
There is a problem in full_cone.cpp in find_new_facets(), which is a very old part of the program (but works very well). With the following patch all tests go through:

```
        if(potential_ranktest)
            convert(Generators_float,Generators);
    }

    #pragma omp parallel private(jj) // <----- we need this private (or must take care of it in another way)
    {
    size_t i,j,k,nr_zero_i;
    boost::dynamic_bitset<> subfacet(dim-2);
    jj = Neg_Subfacet_Multi_United.begin();  // <---- we need this initialization
    size_t jjpos=0;
    int tn = omp_get_ancestor_thread_num(omp_start_level+1);
```
Please add another commit to your pull request.

**Comment by w-bruns** [comment]
Nicer alternative:
```
    #pragma omp parallel
    {
    size_t i,j,k,nr_zero_i;
    boost::dynamic_bitset<> subfacet(dim-2);
    auto jj = Neg_Subfacet_Multi_United.begin();
    size_t jjpos=0;
```

**Comment by fingolfin** [comment]
@w-bruns OK, thanks! PR update, let's see.

**Pull request merged**
