### PR TITLE
Add EXEEXT for windows

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
cc @saraedum, @videlec

**Comment by videlec** [comment]
Is it enough to make the test-suite pass on Windows!?

**Comment by isuruf** [comment]
Yes. (with the static library. For the DLL, see https://github.com/Normaliz/Normaliz/pull/261)

**Comment by videlec** [comment]
Wonderful!

**Comment by saraedum** [comment]
Related: Thanks to @isuruf's heroic efforts, normaliz is available on conda-forge for Windows now. https://github.com/conda-forge/normaliz-feedstock

It's currently still building  but it should  be available in a few hours. So please test if you have a Windows machine handy @w-bruns @slel :)

**Comment by w-bruns** [comment]
Great! I am overwhelmed that this is possible.
Many thanks to Julian and Isuru.
Winfried

**Pull request merged**
